### ISSUE TITLE
want support for `vmadm events`

### ISSUE THREAD

**Issue by bahamas10** [joyent/node-vmadm#2]
This interface will be introduced with OS-2647 (vminfod) and will provide a stream of events for a specific VM or all VMs on a system.

**Comment by bahamas10** [comment]
CR: https://cr.joyent.us/#/c/2798/

Using this test program in the repo:

``` js
#!/usr/node/bin/node

var vmadm = require('./');

var bunyan = require('/usr/node/node_modules/bunyan');
var log = bunyan.createLogger({
    name: 'vmadm',
    level: 'debug',
    serializers: bunyan.stdSerializers
});

var stop = vmadm.events({log: log}, function (ev) {
    // new event
}, function (err) {
    if (err) {
        log.error({err: err}, 'vmadm.events error');
        // this means `vmadm events` is not available on this platform, no need
        // to call stop().
        return;
    }

    // `vmadm events` is available... just stop here.
    stop();
});
```

We can see the following output on:

### machine with vminfod

```
# ./test  | bunyan
[2017-10-17T18:09:59.452Z]  INFO: vmadm/30668 on headnode: calling /usr/sbin/vmadm events -rj
    args: [
      "events",
      "-rj"
    ]
[2017-10-17T18:09:59.820Z] DEBUG: vmadm/30668 on headnode: vmadm event stream ready event (err=null)
[2017-10-17T18:09:59.820Z] DEBUG: vmadm/30668 on headnode: vmadm events stop called
[2017-10-17T18:09:59.838Z]  INFO: vmadm/30668 on headnode: vmadm events stopped (code=143, signal=null)
```

### machine without vminfod

```
# ./test | bunyan
[2017-10-17T18:10:59.601Z]  INFO: vmadm/90292 on datadyne.rapture.com: calling /usr/sbin/vmadm events -rj
    args: [
      "events",
      "-rj"
    ]
[2017-10-17T18:10:59.771Z] ERROR: vmadm/90292 on datadyne.rapture.com: stderr produced (stderr="Invalid command: \"events\".")
[2017-10-17T18:10:59.773Z] DEBUG: vmadm/90292 on datadyne.rapture.com: vmadm event stream ready event
    Error: `vmadm events` not implemented
        at LineStream.<anonymous> (/opt/custom/root/foo/lib/index.js:1294:32)
        at LineStream.EventEmitter.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:408:10)
        at emitReadable (_stream_readable.js:404:5)
        at readableAddChunk (_stream_readable.js:165:9)
        at LineStream.Readable.push (_stream_readable.js:127:10)
        at LineStream.Transform.push (_stream_transform.js:140:32)
        at LineStream._line (/opt/custom/root/foo/node_modules/lstream/linestream.js:60:8)
        at /opt/custom/root/foo/node_modules/lstream/linestream.js:46:10
        at Array.forEach (native)
[2017-10-17T18:10:59.774Z] ERROR: vmadm/90292 on datadyne.rapture.com: vmadm.events error
    Error: `vmadm events` not implemented
        at LineStream.<anonymous> (/opt/custom/root/foo/lib/index.js:1294:32)
        at LineStream.EventEmitter.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:408:10)
        at emitReadable (_stream_readable.js:404:5)
        at readableAddChunk (_stream_readable.js:165:9)
        at LineStream.Readable.push (_stream_readable.js:127:10)
        at LineStream.Transform.push (_stream_transform.js:140:32)
        at LineStream._line (/opt/custom/root/foo/node_modules/lstream/linestream.js:60:8)
        at /opt/custom/root/foo/node_modules/lstream/linestream.js:46:10
        at Array.forEach (native)
[2017-10-17T18:10:59.783Z]  INFO: vmadm/90292 on datadyne.rapture.com: vmadm events stopped (code=143, signal=null)
```

**Comment by bahamas10** [comment]
Testing:  I've been running this version of `node-vmadm` in conjunction with changes to `sdc-vm-agent` (https://cr.joyent.us/#/c/2730/) for about a week now.  `vmadm events` works exactly as expected and the tests pass as expected.   There are a couple failing tests I'm currently debugging but they are not as a result of `vmadm events`.

**Comment by bahamas10** [comment]
merged.
